; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:adafruit_feather_esp32_v2]
platform = espressif32
board = adafruit_feather_esp32_v2
framework = arduino

monitor_speed = 115200

lib_deps =
    adafruit/Adafruit GFX Library @ 1.12.4
    adafruit/Adafruit ILI9341 @ 1.6.3
    adafruit/Adafruit BusIO @ 1.17.4
    adafruit/Adafruit AHTX0 @ 2.0.5
    adafruit/ENS160 - Adafruit Fork @ 3.0.1
    sparkfun/SparkFun MAX3010x Pulse and Proximity Sensor Library @ 1.1.2
    wollewald/MPU9250_WE @ 1.2.17

build_flags =
    -DST7789_DRIVER
    -DTFT_SPI_FREQUENCY=80000000   ; 80 MHz
    -DTFT_DMA_ENABLED
    -DUSE_DMA_TO_TFT
